//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tql.Plugins.Jira {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tql.Plugins.Jira.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Issues.
        /// </summary>
        public static string BoardMatch_AllIssues {
            get {
                return ResourceManager.GetString("BoardMatch_AllIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find issues.
        /// </summary>
        public static string BoardQuickFilterMatch_SearchHint {
            get {
                return ResourceManager.GetString("BoardQuickFilterMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JIRA Board.
        /// </summary>
        public static string BoardsType_Label {
            get {
                return ResourceManager.GetString("BoardsType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Button_Update {
            get {
                return ResourceManager.GetString("Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;re using an API token or your own password, you have to enter your username as well. If you&apos;re using a PAT token, leave the user name field empty..
        /// </summary>
        public static string ConfigurationControl_BasicCredentialsDocumentation {
            get {
                return ResourceManager.GetString("ConfigurationControl_BasicCredentialsDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string ConfigurationControl_Connections {
            get {
                return ResourceManager.GetString("ConfigurationControl_Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string ConfigurationControl_Documentation {
            get {
                return ResourceManager.GetString("ConfigurationControl_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string ConfigurationControl_General {
            get {
                return ResourceManager.GetString("ConfigurationControl_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ConfigurationControl_Name {
            get {
                return ResourceManager.GetString("ConfigurationControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string ConfigurationControl_NameLabel {
            get {
                return ResourceManager.GetString("ConfigurationControl_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string ConfigurationControl_PasswordLabel {
            get {
                return ResourceManager.GetString("ConfigurationControl_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string ConfigurationControl_URL {
            get {
                return ResourceManager.GetString("ConfigurationControl_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL:.
        /// </summary>
        public static string ConfigurationControl_URLLabel {
            get {
                return ResourceManager.GetString("ConfigurationControl_URLLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        public static string ConfigurationControl_UserNameLabel {
            get {
                return ResourceManager.GetString("ConfigurationControl_UserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Dashboard.
        /// </summary>
        public static string DashboardMatch_Label {
            get {
                return ResourceManager.GetString("DashboardMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JIRA Dashboard.
        /// </summary>
        public static string DashboardsType_Label {
            get {
                return ResourceManager.GetString("DashboardsType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JIRA Issue.
        /// </summary>
        public static string IssuesType_Label {
            get {
                return ResourceManager.GetString("IssuesType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JIRA - {0}.
        /// </summary>
        public static string JiraClient_ResourceName {
            get {
                return ResourceManager.GetString("JiraClient_ResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to {0}. Click here to open the {1} settings screen and validate your credentials..
        /// </summary>
        public static string JiraClient_UnableToConnect {
            get {
                return ResourceManager.GetString("JiraClient_UnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JIRA - {0}.
        /// </summary>
        public static string JiraPeopleDirectory_Title {
            get {
                return ResourceManager.GetString("JiraPeopleDirectory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JIRA.
        /// </summary>
        public static string JiraPlugin_Title {
            get {
                return ResourceManager.GetString("JiraPlugin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active sprints.
        /// </summary>
        public static string MatchUtils_ActiveSprints {
            get {
                return ResourceManager.GetString("MatchUtils_ActiveSprints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backlog.
        /// </summary>
        public static string MatchUtils_Backlog {
            get {
                return ResourceManager.GetString("MatchUtils_Backlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        public static string MatchUtils_Board {
            get {
                return ResourceManager.GetString("MatchUtils_Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanban board.
        /// </summary>
        public static string MatchUtils_KanbanBoard {
            get {
                return ResourceManager.GetString("MatchUtils_KanbanBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        public static string MatchUtils_Timeline {
            get {
                return ResourceManager.GetString("MatchUtils_Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        public static string NewsMatch_Query {
            get {
                return ResourceManager.GetString("NewsMatch_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JIRA New.
        /// </summary>
        public static string NewsType_Label {
            get {
                return ResourceManager.GetString("NewsType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Project.
        /// </summary>
        public static string ProjectMatch_Label {
            get {
                return ResourceManager.GetString("ProjectMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find issues.
        /// </summary>
        public static string ProjectMatch_SearchHint {
            get {
                return ResourceManager.GetString("ProjectMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JIRA Project.
        /// </summary>
        public static string ProjectsType_Label {
            get {
                return ResourceManager.GetString("ProjectsType_Label", resourceCulture);
            }
        }
    }
}
