// From https://stackoverflow.com/questions/51578104/how-to-create-a-semi-transparent-or-blurred-backcolor-in-a-windows-form

using System.Runtime.InteropServices;
using System.Security;
using Tql.App.Support;
using Windows.Win32.Graphics.Dwm;

// ReSharper disable UnusedMember.Local
// ReSharper disable UnusedMember.Global
// ReSharper disable InconsistentNaming

namespace Tql.App.Interop;

// These declarations cannot be generated by CsWin32 because they're undocumented.

[SuppressUnmanagedCodeSecurity]
internal static class Dwm
{
    // Undocumented.
    private const DWMWINDOWATTRIBUTE DWMWA_ACCENT_POLICY = (DWMWINDOWATTRIBUTE)19;

    public enum DWMACCENTSTATE
    {
        DWMAS_DISABLED = 0,
        DWMAS_ENABLE_GRADIENT = 1,
        DWMAS_ENABLE_TRANSPARENTGRADIENT = 2,
        DWMAS_ENABLE_BLURBEHIND = 3,
        DWMAS_ENABLE_ACRYLICBLURBEHIND = 4
    }

    [Flags]
    public enum DWMACCENTFLAGS
    {
        DWMAF_DRAW_LEFT_BORDER = 0x20,
        DWMAF_DRAW_TOP_BORDER = 0x40,
        DWMAF_DRAW_RIGHT_BORDER = 0x80,
        DWMAF_DRAW_BOTTOM_BORDER = 0x100,
        DWMAF_DRAW_ALL_BORDERS =
            (
                DWMAF_DRAW_LEFT_BORDER
                | DWMAF_DRAW_TOP_BORDER
                | DWMAF_DRAW_RIGHT_BORDER
                | DWMAF_DRAW_BOTTOM_BORDER
            )
    };

    [StructLayout(LayoutKind.Sequential)]
    public struct ACCENT_POLICY(
        DWMACCENTSTATE accentState,
        DWMACCENTFLAGS accentFlags,
        int gradientColor,
        int animationId
    )
    {
        public DWMACCENTSTATE AccentState = accentState;
        public DWMACCENTFLAGS AccentFlags = accentFlags;
        public int GradientColor = gradientColor;
        public int AnimationId = animationId;
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct WIN_COMPOSITION_ATTR_DATA(
        DWMWINDOWATTRIBUTE attribute,
        IntPtr data,
        int sizeOfData
    )
    {
        public DWMWINDOWATTRIBUTE Attribute = attribute;
        public IntPtr Data = data; // Will point to an AccentPolicy struct, where Attribute will be DWMWINDOWATTRIBUTE.AccentPolicy
        public int SizeOfData = sizeOfData;
    }

    public static void Windows10EnableBlurBehind(IntPtr hWnd)
    {
        var isCreatorsUpdate =
            Environment.OSVersion.Version.CompareTo(OSVersions.Windows10_April2018_CreatorsUpdate)
            >= 0;

        var accPolicy = new ACCENT_POLICY
        {
            AccentState = isCreatorsUpdate
                ? DWMACCENTSTATE.DWMAS_ENABLE_ACRYLICBLURBEHIND
                : DWMACCENTSTATE.DWMAS_ENABLE_BLURBEHIND,
            AccentFlags = DWMACCENTFLAGS.DWMAF_DRAW_ALL_BORDERS
        };

        int accentSize = Marshal.SizeOf(accPolicy);
        IntPtr accentPtr = Marshal.AllocHGlobal(accentSize);
        Marshal.StructureToPtr(accPolicy, accentPtr, false);

        var data = new WIN_COMPOSITION_ATTR_DATA(DWMWA_ACCENT_POLICY, accentPtr, accentSize);

        SetWindowCompositionAttribute(hWnd, ref data);

        Marshal.FreeHGlobal(accentPtr);
    }

    [DllImport("user32", SetLastError = true)]
    internal static extern int SetWindowCompositionAttribute(
        IntPtr hwnd,
        ref WIN_COMPOSITION_ATTR_DATA data
    );
}
