//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tql.App {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tql.App.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        public static string Alert_CopyToClipboard {
            get {
                return ResourceManager.GetString("Alert_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show exception details.
        /// </summary>
        public static string Alert_ShowExceptionDetails {
            get {
                return ResourceManager.GetString("Alert_ShowExceptionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset the &apos;{0}&apos;? This will delete all your data for this environment. This action cannot be undone..
        /// </summary>
        public static string App_AreYouSureResetEnvironment {
            get {
                return ResourceManager.GetString("App_AreYouSureResetEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main environment cannot be reset..
        /// </summary>
        public static string App_CannotResetMainEnvironment {
            get {
                return ResourceManager.GetString("App_CannotResetMainEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not register hot key.
        /// </summary>
        public static string App_CouldNotRegisterHotKey {
            get {
                return ResourceManager.GetString("App_CouldNotRegisterHotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not register the hot key {0}. The reason likely is that it&apos;s in use already. The hot key is disabled. You can change the hot key in the configuration..
        /// </summary>
        public static string App_CouldNotRegisterHotKeySubtitle {
            get {
                return ResourceManager.GetString("App_CouldNotRegisterHotKeySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The environment has been reset..
        /// </summary>
        public static string App_ResetCompletedSuccessfully {
            get {
                return ResourceManager.GetString("App_ResetCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The environment reset has failed with the following error:
        ///
        ///{0}.
        /// </summary>
        public static string App_ResetFailed {
            get {
                return ResourceManager.GetString("App_ResetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Launcher for Techies.
        /// </summary>
        public static string ApplicationShellLinkDescription {
            get {
                return ResourceManager.GetString("ApplicationShellLinkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Techie&apos;s Quick Launcher.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string ConfigurationCategory_Application {
            get {
                return ResourceManager.GetString("ConfigurationCategory_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string ConfigurationWindow_Title {
            get {
                return ResourceManager.GetString("ConfigurationWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t register the hot key..
        /// </summary>
        public static string Error_CouldNotRegisterHotKey {
            get {
                return ResourceManager.GetString("Error_CouldNotRegisterHotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === Caused ===.
        /// </summary>
        public static string ExceptionCausedBy {
            get {
                return ResourceManager.GetString("ExceptionCausedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Bug Report.
        /// </summary>
        public static string FeedbackWindow_CreateBugReport {
            get {
                return ResourceManager.GetString("FeedbackWindow_CreateBugReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Feature Request.
        /// </summary>
        public static string FeedbackWindow_CreateFeatureRequest {
            get {
                return ResourceManager.GetString("FeedbackWindow_CreateFeatureRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use the following technical information in your bug report if you like..
        /// </summary>
        public static string FeedbackWindow_TechnicalInformationForBugReport {
            get {
                return ResourceManager.GetString("FeedbackWindow_TechnicalInformationForBugReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using Techie&apos;s Quick Launcher..
        /// </summary>
        public static string FeedbackWindow_ThankYouForUsingApp {
            get {
                return ResourceManager.GetString("FeedbackWindow_ThankYouForUsingApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string FeedbackWindow_Title {
            get {
                return ResourceManager.GetString("FeedbackWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;d like to leave feedback, you can do so on our GitHub page. You&apos;re welcome to leave a bug report or a feature request. You need a GitHub account to do so..
        /// </summary>
        public static string FeedbackWindow_YouCanLeaveFeedbackOnGitHub {
            get {
                return ResourceManager.GetString("FeedbackWindow_YouCanLeaveFeedbackOnGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string GeneralConfiguration_Appearance {
            get {
                return ResourceManager.GetString("GeneralConfiguration_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string GeneralConfiguration_AreYouSure {
            get {
                return ResourceManager.GetString("GeneralConfiguration_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restart the quick start tutorial?.
        /// </summary>
        public static string GeneralConfiguration_AreYouSureRestartTutorial {
            get {
                return ResourceManager.GetString("GeneralConfiguration_AreYouSureRestartTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines how often the cache is updated. Some plugins will cache data for performance. This setting will set the number of minutes after which the cache will be updated..
        /// </summary>
        public static string GeneralConfiguration_CacheUpdateIntervalHelpText {
            get {
                return ResourceManager.GetString("GeneralConfiguration_CacheUpdateIntervalHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache update interval:.
        /// </summary>
        public static string GeneralConfiguration_CacheUpdateIntervalLabel {
            get {
                return ResourceManager.GetString("GeneralConfiguration_CacheUpdateIntervalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string GeneralConfiguration_CacheUpdateIntervalMinutesLabel {
            get {
                return ResourceManager.GetString("GeneralConfiguration_CacheUpdateIntervalMinutesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralConfiguration_General {
            get {
                return ResourceManager.GetString("GeneralConfiguration_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the number of days of history that&apos;s used..
        /// </summary>
        public static string GeneralConfiguration_HistoryInRootResultsHelpText {
            get {
                return ResourceManager.GetString("GeneralConfiguration_HistoryInRootResultsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History interval:.
        /// </summary>
        public static string GeneralConfiguration_HistoryIntervalLabel {
            get {
                return ResourceManager.GetString("GeneralConfiguration_HistoryIntervalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot key:.
        /// </summary>
        public static string GeneralConfiguration_HotKeyLabel {
            get {
                return ResourceManager.GetString("GeneralConfiguration_HotKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the hot key used to bring up the app..
        /// </summary>
        public static string GeneralConfiguration_HotKeyResetHelpText {
            get {
                return ResourceManager.GetString("GeneralConfiguration_HotKeyResetHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string GeneralConfiguration_LanguageDutch {
            get {
                return ResourceManager.GetString("GeneralConfiguration_LanguageDutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string GeneralConfiguration_LanguageEnglish {
            get {
                return ResourceManager.GetString("GeneralConfiguration_LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the language requires you to restart the application..
        /// </summary>
        public static string GeneralConfiguration_LanguageHelpText {
            get {
                return ResourceManager.GetString("GeneralConfiguration_LanguageHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string GeneralConfiguration_LanguageLabel {
            get {
                return ResourceManager.GetString("GeneralConfiguration_LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string GeneralConfiguration_LanguageSystem {
            get {
                return ResourceManager.GetString("GeneralConfiguration_LanguageSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main window tint:.
        /// </summary>
        public static string GeneralConfiguration_MainWindowTintLabel {
            get {
                return ResourceManager.GetString("GeneralConfiguration_MainWindowTintLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies an outer glow to the text and images on the search window. This can increase readability..
        /// </summary>
        public static string GeneralConfiguration_OuterGlowRadiusHelpText {
            get {
                return ResourceManager.GetString("GeneralConfiguration_OuterGlowRadiusHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outer glow radius:.
        /// </summary>
        public static string GeneralConfiguration_OuterGlowRadiusLabel {
            get {
                return ResourceManager.GetString("GeneralConfiguration_OuterGlowRadiusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart required.
        /// </summary>
        public static string GeneralConfiguration_RestartRequired {
            get {
                return ResourceManager.GetString("GeneralConfiguration_RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve changed settings that require a restart of the application..
        /// </summary>
        public static string GeneralConfiguration_RestartRequiredHelpText {
            get {
                return ResourceManager.GetString("GeneralConfiguration_RestartRequiredHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Tutorial.
        /// </summary>
        public static string GeneralConfiguration_RestartTutorial {
            get {
                return ResourceManager.GetString("GeneralConfiguration_RestartTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the quick start tutorial..
        /// </summary>
        public static string GeneralConfiguration_RestartTutorialHelpText {
            get {
                return ResourceManager.GetString("GeneralConfiguration_RestartTutorialHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search result font size:.
        /// </summary>
        public static string GeneralConfiguration_SearchResultFontSizeLabel {
            get {
                return ResourceManager.GetString("GeneralConfiguration_SearchResultFontSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to points.
        /// </summary>
        public static string GeneralConfiguration_SearchResultFontSizePointsLabel {
            get {
                return ResourceManager.GetString("GeneralConfiguration_SearchResultFontSizePointsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on screen:.
        /// </summary>
        public static string GeneralConfiguration_ShowOnScreenLabel {
            get {
                return ResourceManager.GetString("GeneralConfiguration_ShowOnScreenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telemetry.
        /// </summary>
        public static string GeneralConfiguration_Telemetry {
            get {
                return ResourceManager.GetString("GeneralConfiguration_Telemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the theme requires you to restart the application..
        /// </summary>
        public static string GeneralConfiguration_ThemeHelpText {
            get {
                return ResourceManager.GetString("GeneralConfiguration_ThemeHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        public static string GeneralConfiguration_ThemeLabel {
            get {
                return ResourceManager.GetString("GeneralConfiguration_ThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only tracks anonymous performance and usage metrics..
        /// </summary>
        public static string GeneralConfiguration_TrackAnonymousMetricsHelpText {
            get {
                return ResourceManager.GetString("GeneralConfiguration_TrackAnonymousMetricsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track anonymous metrics.
        /// </summary>
        public static string GeneralConfiguration_TrackAnonymousMetricsLabel {
            get {
                return ResourceManager.GetString("GeneralConfiguration_TrackAnonymousMetricsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors may capture PII (personally identifiable information) data like your user name because of system information that&apos;s included automatically when tracking errors..
        /// </summary>
        public static string GeneralConfiguration_TrackErrorsHelpText {
            get {
                return ResourceManager.GetString("GeneralConfiguration_TrackErrorsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track errors.
        /// </summary>
        public static string GeneralConfiguration_TrackErrorsLabel {
            get {
                return ResourceManager.GetString("GeneralConfiguration_TrackErrorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set hot key.
        /// </summary>
        public static string GeneralConfiguration_UnableToSetHotKey {
            get {
                return ResourceManager.GetString("GeneralConfiguration_UnableToSetHotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hot key could not be configured. The combination might be invalid or it may already be in use. Please use a different key combination and try again..
        /// </summary>
        public static string GeneralConfiguration_UnableToSetHotKeyHelpText {
            get {
                return ResourceManager.GetString("GeneralConfiguration_UnableToSetHotKeyHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Drive.
        /// </summary>
        public static string GoogleDriveBackupProvider_Label {
            get {
                return ResourceManager.GetString("GoogleDriveBackupProvider_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string HotKeyAddKey {
            get {
                return ResourceManager.GetString("HotKeyAddKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt.
        /// </summary>
        public static string HotKeyAlt {
            get {
                return ResourceManager.GetString("HotKeyAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backspace.
        /// </summary>
        public static string HotKeyBackspaceKey {
            get {
                return ResourceManager.GetString("HotKeyBackspaceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Back.
        /// </summary>
        public static string HotKeyBrowserBackKey {
            get {
                return ResourceManager.GetString("HotKeyBrowserBackKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Favorites.
        /// </summary>
        public static string HotKeyBrowserFavoritesKey {
            get {
                return ResourceManager.GetString("HotKeyBrowserFavoritesKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Forward.
        /// </summary>
        public static string HotKeyBrowserForwardKey {
            get {
                return ResourceManager.GetString("HotKeyBrowserForwardKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Refresh.
        /// </summary>
        public static string HotKeyBrowserRefreshKey {
            get {
                return ResourceManager.GetString("HotKeyBrowserRefreshKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Search.
        /// </summary>
        public static string HotKeyBrowserSearchKey {
            get {
                return ResourceManager.GetString("HotKeyBrowserSearchKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Start and Home.
        /// </summary>
        public static string HotKeyBrowserStartAndHomeKey {
            get {
                return ResourceManager.GetString("HotKeyBrowserStartAndHomeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Stop.
        /// </summary>
        public static string HotKeyBrowserStopKey {
            get {
                return ResourceManager.GetString("HotKeyBrowserStopKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string HotKeyClearKey {
            get {
                return ResourceManager.GetString("HotKeyClearKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string HotKeyControl {
            get {
                return ResourceManager.GetString("HotKeyControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        public static string HotKeyDecimalKey {
            get {
                return ResourceManager.GetString("HotKeyDecimalKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string HotKeyDelKey {
            get {
                return ResourceManager.GetString("HotKeyDelKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divide.
        /// </summary>
        public static string HotKeyDivideKey {
            get {
                return ResourceManager.GetString("HotKeyDivideKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down Arrow.
        /// </summary>
        public static string HotKeyDownArrowKey {
            get {
                return ResourceManager.GetString("HotKeyDownArrowKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string HotKeyEndKey {
            get {
                return ResourceManager.GetString("HotKeyEndKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string HotKeyEnterKey {
            get {
                return ResourceManager.GetString("HotKeyEnterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esc.
        /// </summary>
        public static string HotKeyEscKey {
            get {
                return ResourceManager.GetString("HotKeyEscKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        public static string HotKeyExecuteKey {
            get {
                return ResourceManager.GetString("HotKeyExecuteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HotKeyHelpKey {
            get {
                return ResourceManager.GetString("HotKeyHelpKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HotKeyHomeKey {
            get {
                return ResourceManager.GetString("HotKeyHomeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string HotKeyInsKey {
            get {
                return ResourceManager.GetString("HotKeyInsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Arrow.
        /// </summary>
        public static string HotKeyLeftArrowKey {
            get {
                return ResourceManager.GetString("HotKeyLeftArrowKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiply.
        /// </summary>
        public static string HotKeyMultiplyKey {
            get {
                return ResourceManager.GetString("HotKeyMultiplyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Track.
        /// </summary>
        public static string HotKeyNextTrackKey {
            get {
                return ResourceManager.GetString("HotKeyNextTrackKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric pad {0}.
        /// </summary>
        public static string HotKeyNumericPadKey {
            get {
                return ResourceManager.GetString("HotKeyNumericPadKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Down.
        /// </summary>
        public static string HotKeyPageDownKey {
            get {
                return ResourceManager.GetString("HotKeyPageDownKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Up.
        /// </summary>
        public static string HotKeyPageUpKey {
            get {
                return ResourceManager.GetString("HotKeyPageUpKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string HotKeyPauseKey {
            get {
                return ResourceManager.GetString("HotKeyPauseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play/Pause Media.
        /// </summary>
        public static string HotKeyPlayPauseMediaKey {
            get {
                return ResourceManager.GetString("HotKeyPlayPauseMediaKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Track.
        /// </summary>
        public static string HotKeyPreviousTrackKey {
            get {
                return ResourceManager.GetString("HotKeyPreviousTrackKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string HotKeyPrintKey {
            get {
                return ResourceManager.GetString("HotKeyPrintKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Screen.
        /// </summary>
        public static string HotKeyPrintScreenKey {
            get {
                return ResourceManager.GetString("HotKeyPrintScreenKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Arrow.
        /// </summary>
        public static string HotKeyRightArrowKey {
            get {
                return ResourceManager.GetString("HotKeyRightArrowKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string HotKeySelectKey {
            get {
                return ResourceManager.GetString("HotKeySelectKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Media.
        /// </summary>
        public static string HotKeySelectMediaKey {
            get {
                return ResourceManager.GetString("HotKeySelectMediaKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator.
        /// </summary>
        public static string HotKeySeparatorKey {
            get {
                return ResourceManager.GetString("HotKeySeparatorKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string HotKeyShift {
            get {
                return ResourceManager.GetString("HotKeyShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacebar.
        /// </summary>
        public static string HotKeySpacebarKey {
            get {
                return ResourceManager.GetString("HotKeySpacebarKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Application 1.
        /// </summary>
        public static string HotKeyStartApplication1Key {
            get {
                return ResourceManager.GetString("HotKeyStartApplication1Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Application 2.
        /// </summary>
        public static string HotKeyStartApplication2Key {
            get {
                return ResourceManager.GetString("HotKeyStartApplication2Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Mail.
        /// </summary>
        public static string HotKeyStartMailKey {
            get {
                return ResourceManager.GetString("HotKeyStartMailKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Media.
        /// </summary>
        public static string HotKeyStopMediaKey {
            get {
                return ResourceManager.GetString("HotKeyStopMediaKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract.
        /// </summary>
        public static string HotKeySubtractKey {
            get {
                return ResourceManager.GetString("HotKeySubtractKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        public static string HotKeyTabKey {
            get {
                return ResourceManager.GetString("HotKeyTabKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up Arrow.
        /// </summary>
        public static string HotKeyUpArrowKey {
            get {
                return ResourceManager.GetString("HotKeyUpArrowKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Down.
        /// </summary>
        public static string HotKeyVolumeDownKey {
            get {
                return ResourceManager.GetString("HotKeyVolumeDownKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Mute.
        /// </summary>
        public static string HotKeyVolumeMuteKey {
            get {
                return ResourceManager.GetString("HotKeyVolumeMuteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Up.
        /// </summary>
        public static string HotKeyVolumeUpKey {
            get {
                return ResourceManager.GetString("HotKeyVolumeUpKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win.
        /// </summary>
        public static string HotKeyWindows {
            get {
                return ResourceManager.GetString("HotKeyWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to authenticate.
        /// </summary>
        public static string InteractiveAuthenticationWindow_FailedToAuthenticate {
            get {
                return ResourceManager.GetString("InteractiveAuthenticationWindow_FailedToAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following resource requires your credentials:.
        /// </summary>
        public static string InteractiveAuthenticationWindow_TheFollowingResourceRequiresYourCredentialsLabel {
            get {
                return ResourceManager.GetString("InteractiveAuthenticationWindow_TheFollowingResourceRequiresYourCredentialsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache is being updated.
        /// </summary>
        public static string MainWindow_CacheIsBeingUpdated {
            get {
                return ResourceManager.GetString("MainWindow_CacheIsBeingUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cache of one or more plugins is being updated..
        /// </summary>
        public static string MainWindow_CacheIsBeingUpdatedHelpText {
            get {
                return ResourceManager.GetString("MainWindow_CacheIsBeingUpdatedHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string MainWindow_Configuration {
            get {
                return ResourceManager.GetString("MainWindow_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help &amp; documentation.
        /// </summary>
        public static string MainWindow_HelpAndDocumentation {
            get {
                return ResourceManager.GetString("MainWindow_HelpAndDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to result.
        /// </summary>
        public static string MainWindow_LaunchRunnablePostfix {
            get {
                return ResourceManager.GetString("MainWindow_LaunchRunnablePostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string MainWindow_LaunchRunnablePrefix {
            get {
                return ResourceManager.GetString("MainWindow_LaunchRunnablePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave feedback for the developers.
        /// </summary>
        public static string MainWindow_LeaveFeedback {
            get {
                return ResourceManager.GetString("MainWindow_LeaveFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave ideas, features suggestions or bug reports for the developers..
        /// </summary>
        public static string MainWindow_LeaveFeedbackHelpText {
            get {
                return ResourceManager.GetString("MainWindow_LeaveFeedbackHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link copied.
        /// </summary>
        public static string MainWindow_LinkCopied {
            get {
                return ResourceManager.GetString("MainWindow_LinkCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category.
        /// </summary>
        public static string MainWindow_OpenCategoryPostfix {
            get {
                return ResourceManager.GetString("MainWindow_OpenCategoryPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string MainWindow_OpenCategoryPrefix {
            get {
                return ResourceManager.GetString("MainWindow_OpenCategoryPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open TQL.
        /// </summary>
        public static string MainWindow_OpenTQL {
            get {
                return ResourceManager.GetString("MainWindow_OpenTQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string MainWindow_SearchingToolTip {
            get {
                return ResourceManager.GetString("MainWindow_SearchingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        public static string NotifyIconManager_ApplicationIsStarting {
            get {
                return ResourceManager.GetString("NotifyIconManager_ApplicationIsStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        public static string NotifyIconManager_ApplicationIsUpdating {
            get {
                return ResourceManager.GetString("NotifyIconManager_ApplicationIsUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Configuration.
        /// </summary>
        public static string NotifyMenu_ConfigurationLabel {
            get {
                return ResourceManager.GetString("NotifyMenu_ConfigurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        public static string NotifyMenu_ExitLabel {
            get {
                return ResourceManager.GetString("NotifyMenu_ExitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        public static string NotifyMenu_HelpLabel {
            get {
                return ResourceManager.GetString("NotifyMenu_HelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalidate All Caches.
        /// </summary>
        public static string NotifyMenu_InvalidateAllCachesLabel {
            get {
                return ResourceManager.GetString("NotifyMenu_InvalidateAllCachesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Search.
        /// </summary>
        public static string NotifyMenu_SearchLabel {
            get {
                return ResourceManager.GetString("NotifyMenu_SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding dependencies....
        /// </summary>
        public static string NuGetClient_FindingDependencies {
            get {
                return ResourceManager.GetString("NuGetClient_FindingDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        public static string NuGetClient_Installing {
            get {
                return ResourceManager.GetString("NuGetClient_Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed {0}.
        /// </summary>
        public static string NuGetClient_PackageInstalled {
            get {
                return ResourceManager.GetString("NuGetClient_PackageInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying package....
        /// </summary>
        public static string PackageManager_DeployingPackage {
            get {
                return ResourceManager.GetString("PackageManager_DeployingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting package metadata....
        /// </summary>
        public static string PackageManager_GettingPackageMetadata {
            get {
                return ResourceManager.GetString("PackageManager_GettingPackageMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring {0}....
        /// </summary>
        public static string PackageManager_RestoringPackage {
            get {
                return ResourceManager.GetString("PackageManager_RestoringPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating {0}....
        /// </summary>
        public static string PackageManager_UpdatingPackage {
            get {
                return ResourceManager.GetString("PackageManager_UpdatingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;re using a PAT token to connect to an Azure DevOps private artifact feed, enter it into the password field and enter the part of your email address before the @ into the user name field..
        /// </summary>
        public static string PackageSourceEditWindow_PasswordHelpText {
            get {
                return ResourceManager.GetString("PackageSourceEditWindow_PasswordHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string PackageSourceEditWindow_PasswordLabel {
            get {
                return ResourceManager.GetString("PackageSourceEditWindow_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Package Source.
        /// </summary>
        public static string PackageSourceEditWindow_Title {
            get {
                return ResourceManager.GetString("PackageSourceEditWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL:.
        /// </summary>
        public static string PackageSourceEditWindow_URLLabel {
            get {
                return ResourceManager.GetString("PackageSourceEditWindow_URLLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        public static string PackageSourceEditWindow_UserNameLabel {
            get {
                return ResourceManager.GetString("PackageSourceEditWindow_UserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Sources.
        /// </summary>
        public static string PackageSourcesConfiguration_PackageSources {
            get {
                return ResourceManager.GetString("PackageSourcesConfiguration_PackageSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string PackageSourcesConfiguration_URL {
            get {
                return ResourceManager.GetString("PackageSourcesConfiguration_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing new plugin....
        /// </summary>
        public static string PackageStoreLoader_InitializingPackage {
            get {
                return ResourceManager.GetString("PackageStoreLoader_InitializingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting unused files....
        /// </summary>
        public static string PackageStoreManager_DeletingUnusedFiles {
            get {
                return ResourceManager.GetString("PackageStoreManager_DeletingUnusedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package &apos;{0}&apos; failed to load.
        /// </summary>
        public static string PluginManager_PackageFailedToLoad {
            get {
                return ResourceManager.GetString("PluginManager_PackageFailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occurred while loading the &apos;{0}&apos; package: {1}.
        ///
        ///Do you want to restart TQL to see if this resolves the issue?.
        /// </summary>
        public static string PluginManager_PackageFailedToLoadSubtitle {
            get {
                return ResourceManager.GetString("PluginManager_PackageFailedToLoadSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin &apos;{0}&apos; failed to load.
        /// </summary>
        public static string PluginManager_PluginFailedToLoad {
            get {
                return ResourceManager.GetString("PluginManager_PluginFailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occurred while loading the &apos;{0}&apos; plugin: {1}.
        ///
        ///Do you want to restart TQL to see if this resolves the issue?.
        /// </summary>
        public static string PluginManager_PluginFailedToLoadSubtitle {
            get {
                return ResourceManager.GetString("PluginManager_PluginFailedToLoadSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string PluginsConfiguration_Browse {
            get {
                return ResourceManager.GetString("PluginsConfiguration_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string PluginsConfiguration_Installed {
            get {
                return ResourceManager.GetString("PluginsConfiguration_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string PluginsConfiguration_InstallLabel {
            get {
                return ResourceManager.GetString("PluginsConfiguration_InstallLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string PluginsConfiguration_Local {
            get {
                return ResourceManager.GetString("PluginsConfiguration_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin comes from a local package source..
        /// </summary>
        public static string PluginsConfiguration_LocalToolTip {
            get {
                return ResourceManager.GetString("PluginsConfiguration_LocalToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string PluginsConfiguration_PluginBy {
            get {
                return ResourceManager.GetString("PluginsConfiguration_PluginBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloads.
        /// </summary>
        public static string PluginsConfiguration_PluginDownloads {
            get {
                return ResourceManager.GetString("PluginsConfiguration_PluginDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin installation failed.
        /// </summary>
        public static string PluginsConfiguration_PluginInstallationFailed {
            get {
                return ResourceManager.GetString("PluginsConfiguration_PluginInstallationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string PluginsConfiguration_Plugins {
            get {
                return ResourceManager.GetString("PluginsConfiguration_Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string PluginsConfiguration_RemoveLabel {
            get {
                return ResourceManager.GetString("PluginsConfiguration_RemoveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Techie&apos;s Quick Launcher to complete the installation.
        /// </summary>
        public static string PluginsConfiguration_RestartHelpText {
            get {
                return ResourceManager.GetString("PluginsConfiguration_RestartHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string PluginsConfiguration_RestartLabel {
            get {
                return ResourceManager.GetString("PluginsConfiguration_RestartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to install this plugin?.
        /// </summary>
        public static string PluginsConfiguration_UnverifiedSource {
            get {
                return ResourceManager.GetString("PluginsConfiguration_UnverifiedSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin comes from an unverified source. Are you sure you want to install this plugin?.
        /// </summary>
        public static string PluginsConfiguration_UnverifiedSourceSubtitle {
            get {
                return ResourceManager.GetString("PluginsConfiguration_UnverifiedSourceSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        public static string PluginsConfiguration_Verified {
            get {
                return ResourceManager.GetString("PluginsConfiguration_Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin comes from a verified source..
        /// </summary>
        public static string PluginsConfiguration_VerifiedToolTip {
            get {
                return ResourceManager.GetString("PluginsConfiguration_VerifiedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon:.
        /// </summary>
        public static string ProfileEditWindow_IconLabel {
            get {
                return ResourceManager.GetString("ProfileEditWindow_IconLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string ProfileEditWindow_Title {
            get {
                return ResourceManager.GetString("ProfileEditWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string ProfileEditWindow_TitleLabel {
            get {
                return ResourceManager.GetString("ProfileEditWindow_TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Profile.
        /// </summary>
        public static string ProfileManager_DefaultProfile {
            get {
                return ResourceManager.GetString("ProfileManager_DefaultProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string ProfilesConfiguration_AreYouSureDeleteProfile {
            get {
                return ResourceManager.GetString("ProfilesConfiguration_AreYouSureDeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this profile? All data associated with this profile will be deleted..
        /// </summary>
        public static string ProfilesConfiguration_AreYouSureDeleteProfileSubtitle {
            get {
                return ResourceManager.GetString("ProfilesConfiguration_AreYouSureDeleteProfileSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current profile cannot be deleted.
        /// </summary>
        public static string ProfilesConfiguration_CannotDeleteCurrentProfile {
            get {
                return ResourceManager.GetString("ProfilesConfiguration_CannotDeleteCurrentProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile you&apos;re trying to delete is the current profile of the app. If you want to delete this profile, you need to close the current app and delete it from a different profile..
        /// </summary>
        public static string ProfilesConfiguration_CannotDeleteCurrentProfileSubtitle {
            get {
                return ResourceManager.GetString("ProfilesConfiguration_CannotDeleteCurrentProfileSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default profile cannot be deleted.
        /// </summary>
        public static string ProfilesConfiguration_CannotDeleteDefaultProfile {
            get {
                return ResourceManager.GetString("ProfilesConfiguration_CannotDeleteDefaultProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile could not be deleted. Make sure you close the instance of the app with this profile before you delete the profile..
        /// </summary>
        public static string ProfilesConfiguration_CouldNotDeleteProfile {
            get {
                return ResourceManager.GetString("ProfilesConfiguration_CouldNotDeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new profile has been created.
        /// </summary>
        public static string ProfilesConfiguration_CreatedNewProfile {
            get {
                return ResourceManager.GetString("ProfilesConfiguration_CreatedNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new shortcut has been added to the start menu. You can open the app with your new profile by opening the shortcut. The profile will also start automatically when your computer starts up.
        ///
        ///Don&apos;t forget to change the hotkey for your new profile. You can do this in the general configuration page..
        /// </summary>
        public static string ProfilesConfiguration_CreatedNewProfileSubtitle {
            get {
                return ResourceManager.GetString("ProfilesConfiguration_CreatedNewProfileSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string ProfilesConfiguration_Profiles {
            get {
                return ResourceManager.GetString("ProfilesConfiguration_Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string ProfilesConfiguration_Title {
            get {
                return ResourceManager.GetString("ProfilesConfiguration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One moment please....
        /// </summary>
        public static string ProgressWindow_OneMomentPlease {
            get {
                return ResourceManager.GetString("ProgressWindow_OneMomentPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string ProgressWindow_Title {
            get {
                return ResourceManager.GetString("ProgressWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to the previous step..
        /// </summary>
        public static string QuickStartWindow_PreviousStep {
            get {
                return ResourceManager.GetString("QuickStartWindow_PreviousStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search failed with an error.
        /// </summary>
        public static string SearchManager_SearchFailedWithError {
            get {
                return ResourceManager.GetString("SearchManager_SearchFailedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search failed with the following error message:.
        /// </summary>
        public static string SearchManager_SearchFailedWithErrorMessage {
            get {
                return ResourceManager.GetString("SearchManager_SearchFailedWithErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy a link to the search results to the clipboard..
        /// </summary>
        public static string SearchResultControl_CopyMatchLinkHelpText {
            get {
                return ResourceManager.GetString("SearchResultControl_CopyMatchLinkHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search result can be launched.
        /// </summary>
        public static string SearchResultControl_MatchCanBeLaunched {
            get {
                return ResourceManager.GetString("SearchResultControl_MatchCanBeLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This search result is for something you can launch. Click on it, or press Enter to launch the search result..
        /// </summary>
        public static string SearchResultControl_MatchCanBeLaunchedHelpText {
            get {
                return ResourceManager.GetString("SearchResultControl_MatchCanBeLaunchedHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search result is a category.
        /// </summary>
        public static string SearchResultControl_MatchContainsSubItems {
            get {
                return ResourceManager.GetString("SearchResultControl_MatchContainsSubItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This search result is a category and can it self be searched. Press Tab to enter the category to search in it..
        /// </summary>
        public static string SearchResultControl_MatchContainsSubItemsHelpText {
            get {
                return ResourceManager.GetString("SearchResultControl_MatchContainsSubItemsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin search result.
        /// </summary>
        public static string SearchResultControl_PinSearchResult {
            get {
                return ResourceManager.GetString("SearchResultControl_PinSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin the search result to have them sorted to the top of the list..
        /// </summary>
        public static string SearchResultControl_PinSearchResultHelpText {
            get {
                return ResourceManager.GetString("SearchResultControl_PinSearchResultHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove search result from the history.
        /// </summary>
        public static string SearchResultControl_RemoveMatchFromHistoryHelpText {
            get {
                return ResourceManager.GetString("SearchResultControl_RemoveMatchFromHistoryHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin search result.
        /// </summary>
        public static string SearchResultControl_UnpinSearchResultHelpText {
            get {
                return ResourceManager.GetString("SearchResultControl_UnpinSearchResultHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sideloading plugin....
        /// </summary>
        public static string SideloadedPackageLoader_LoadingPackage {
            get {
                return ResourceManager.GetString("SideloadedPackageLoader_LoadingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Techie&apos;s Quick Launcher is starting....
        /// </summary>
        public static string SplashScreenWindow_Starting {
            get {
                return ResourceManager.GetString("SplashScreenWindow_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove your {0} account?.
        /// </summary>
        public static string SynchronizationConfiguration_AreYouSureRemoveService {
            get {
                return ResourceManager.GetString("SynchronizationConfiguration_AreYouSureRemoveService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup found.
        /// </summary>
        public static string SynchronizationConfiguration_BackupAvailable {
            get {
                return ResourceManager.GetString("SynchronizationConfiguration_BackupAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A backup was found in your {0} account. Do you want to restore this backup?.
        /// </summary>
        public static string SynchronizationConfiguration_BackupAvailableSubtitle {
            get {
                return ResourceManager.GetString("SynchronizationConfiguration_BackupAvailableSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Drive:.
        /// </summary>
        public static string SynchronizationConfiguration_GoogleDriveLabel {
            get {
                return ResourceManager.GetString("SynchronizationConfiguration_GoogleDriveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string SynchronizationConfiguration_Remove {
            get {
                return ResourceManager.GetString("SynchronizationConfiguration_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to restore backup.
        /// </summary>
        public static string SynchronizationConfiguration_RestoreFailed {
            get {
                return ResourceManager.GetString("SynchronizationConfiguration_RestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup couldn&apos;t be restored. Do you want to keep this account? The existing backup will be overwritten..
        /// </summary>
        public static string SynchronizationConfiguration_RestoreFailedSubtitle {
            get {
                return ResourceManager.GetString("SynchronizationConfiguration_RestoreFailedSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string SynchronizationConfiguration_Setup {
            get {
                return ResourceManager.GetString("SynchronizationConfiguration_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization with {0} has been setup successfully.
        /// </summary>
        public static string SynchronizationConfiguration_SetupComplete {
            get {
                return ResourceManager.GetString("SynchronizationConfiguration_SetupComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to setup synchronization.
        /// </summary>
        public static string SynchronizationConfiguration_SetupFailed {
            get {
                return ResourceManager.GetString("SynchronizationConfiguration_SetupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization.
        /// </summary>
        public static string SynchronizationConfiguration_Synchronization {
            get {
                return ResourceManager.GetString("SynchronizationConfiguration_Synchronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization:.
        /// </summary>
        public static string SynchronizationConfiguration_SynchronizationLabel {
            get {
                return ResourceManager.GetString("SynchronizationConfiguration_SynchronizationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize Now.
        /// </summary>
        public static string SynchronizationConfiguration_SynchronizationNow {
            get {
                return ResourceManager.GetString("SynchronizationConfiguration_SynchronizationNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started synchronization.
        /// </summary>
        public static string SynchronizationConfiguration_SynchronizationStarted {
            get {
                return ResourceManager.GetString("SynchronizationConfiguration_SynchronizationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last synchronized at {0}.
        /// </summary>
        public static string SynchronizationService_LastSynchronized {
            get {
                return ResourceManager.GetString("SynchronizationService_LastSynchronized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization pending.
        /// </summary>
        public static string SynchronizationService_SynchronizationPending {
            get {
                return ResourceManager.GetString("SynchronizationService_SynchronizationPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing....
        /// </summary>
        public static string SynchronizationService_Synchronizing {
            get {
                return ResourceManager.GetString("SynchronizationService_Synchronizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Terms of Service has been updated. Click here to review the latest version..
        /// </summary>
        public static string TermsOfServiceNotificationService_Updated {
            get {
                return ResourceManager.GetString("TermsOfServiceNotificationService_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string ThemeSystem {
            get {
                return ResourceManager.GetString("ThemeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update....
        /// </summary>
        public static string UpdateChecker_DownloadingUpdate {
            get {
                return ResourceManager.GetString("UpdateChecker_DownloadingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing update....
        /// </summary>
        public static string UpdateChecker_InstallingUpdate {
            get {
                return ResourceManager.GetString("UpdateChecker_InstallingUpdate", resourceCulture);
            }
        }
    }
}
