//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tql.Plugins.AzureDevOps {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tql.Plugins.AzureDevOps.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure DevOps - {0}.
        /// </summary>
        public static string AzureDevOpsApi_ResourceName {
            get {
                return ResourceManager.GetString("AzureDevOpsApi_ResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to {0}. Click here to reconnect..
        /// </summary>
        public static string AzureDevOpsApi_UnableToConnect {
            get {
                return ResourceManager.GetString("AzureDevOpsApi_UnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure DevOps - {0}.
        /// </summary>
        public static string AzureDevOpsPeopleDirectory_Name {
            get {
                return ResourceManager.GetString("AzureDevOpsPeopleDirectory_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure DevOps.
        /// </summary>
        public static string AzureDevOpsPlugin_Title {
            get {
                return ResourceManager.GetString("AzureDevOpsPlugin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Backlog.
        /// </summary>
        public static string BacklogMatch_Label {
            get {
                return ResourceManager.GetString("BacklogMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Backlog.
        /// </summary>
        public static string BacklogsType_Label {
            get {
                return ResourceManager.GetString("BacklogsType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Board.
        /// </summary>
        public static string BoardMatch_Label {
            get {
                return ResourceManager.GetString("BoardMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Board.
        /// </summary>
        public static string BoardsType_Label {
            get {
                return ResourceManager.GetString("BoardsType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Button_Update {
            get {
                return ResourceManager.GetString("Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string ConfigurationControl_Connections {
            get {
                return ResourceManager.GetString("ConfigurationControl_Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string ConfigurationControl_General {
            get {
                return ResourceManager.GetString("ConfigurationControl_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ConfigurationControl_Name {
            get {
                return ResourceManager.GetString("ConfigurationControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string ConfigurationControl_NameLabel {
            get {
                return ResourceManager.GetString("ConfigurationControl_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string ConfigurationControl_URL {
            get {
                return ResourceManager.GetString("ConfigurationControl_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL:.
        /// </summary>
        public static string ConfigurationControl_URLLabel {
            get {
                return ResourceManager.GetString("ConfigurationControl_URLLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Dashboard.
        /// </summary>
        public static string DashboardMatch_Label {
            get {
                return ResourceManager.GetString("DashboardMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Dashboard.
        /// </summary>
        public static string DashboardsType_Label {
            get {
                return ResourceManager.GetString("DashboardsType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {0}.
        /// </summary>
        public static string NewMatch_NewIssueType {
            get {
                return ResourceManager.GetString("NewMatch_NewIssueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Query.
        /// </summary>
        public static string NewMatch_NewQuery {
            get {
                return ResourceManager.GetString("NewMatch_NewQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure New.
        /// </summary>
        public static string NewsType_Label {
            get {
                return ResourceManager.GetString("NewsType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Pipeline.
        /// </summary>
        public static string PipelinesType_Label {
            get {
                return ResourceManager.GetString("PipelinesType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Query.
        /// </summary>
        public static string QueriesType_Label {
            get {
                return ResourceManager.GetString("QueriesType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Repository.
        /// </summary>
        public static string RepositoriesType_Label {
            get {
                return ResourceManager.GetString("RepositoriesType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find files.
        /// </summary>
        public static string RepositoryMatch_FindFiles {
            get {
                return ResourceManager.GetString("RepositoryMatch_FindFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Work Item.
        /// </summary>
        public static string WorkItemsType_Label {
            get {
                return ResourceManager.GetString("WorkItemsType_Label", resourceCulture);
            }
        }
    }
}
