//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tql.Plugins.Demo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tql.Plugins.Demo.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo Plugin.
        /// </summary>
        public static string DemoesMatch_Label {
            get {
                return ResourceManager.GetString("DemoesMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find demo data.
        /// </summary>
        public static string DemoesMatch_SearchHint {
            get {
                return ResourceManager.GetString("DemoesMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TQL Website.
        /// </summary>
        public static string DemoMatch_Label {
            get {
                return ResourceManager.GetString("DemoMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Demo.
        /// </summary>
        public static string DemoPeopleDirectory_EnglishLabel {
            get {
                return ResourceManager.GetString("DemoPeopleDirectory_EnglishLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Demo.
        /// </summary>
        public static string DemoPeopleDirectory_FrenchLabel {
            get {
                return ResourceManager.GetString("DemoPeopleDirectory_FrenchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo Plugin.
        /// </summary>
        public static string DemoPlugin_Label {
            get {
                return ResourceManager.GetString("DemoPlugin_Label", resourceCulture);
            }
        }
    }
}
