//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tql.Plugins.GitHub {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tql.Plugins.GitHub.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Button_Documentation {
            get {
                return ResourceManager.GetString("Button_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string ConfigurationControl_Connections {
            get {
                return ResourceManager.GetString("ConfigurationControl_Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string ConfigurationControl_General {
            get {
                return ResourceManager.GetString("ConfigurationControl_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ConfigurationControl_Name {
            get {
                return ResourceManager.GetString("ConfigurationControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string ConnectionEditWindow_NameLabel {
            get {
                return ResourceManager.GetString("ConnectionEditWindow_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Connection.
        /// </summary>
        public static string ConnectionEditWindow_Title {
            get {
                return ResourceManager.GetString("ConnectionEditWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Gist.
        /// </summary>
        public static string GistsMatch_Label {
            get {
                return ResourceManager.GetString("GistsMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My GitHub Gist.
        /// </summary>
        public static string GistsMatch_MyLabel {
            get {
                return ResourceManager.GetString("GistsMatch_MyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find gists.
        /// </summary>
        public static string GistsMatch_SearchHint {
            get {
                return ResourceManager.GetString("GistsMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub - {0}.
        /// </summary>
        public static string GitHubApi_ResourceName {
            get {
                return ResourceManager.GetString("GitHubApi_ResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to {0}. Click here to reconnect..
        /// </summary>
        public static string GitHubApi_UnableToConnect {
            get {
                return ResourceManager.GetString("GitHubApi_UnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication completed. You can now go back to the app..
        /// </summary>
        public static string GitHubOAuthWorkflow_AuthenticationComplete {
            get {
                return ResourceManager.GetString("GitHubOAuthWorkflow_AuthenticationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string GitHubPlugin_Title {
            get {
                return ResourceManager.GetString("GitHubPlugin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find issues.
        /// </summary>
        public static string IssuesMatch_SearchHint {
            get {
                return ResourceManager.GetString("IssuesMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        public static string IssuesMatchBase_IssueLabel {
            get {
                return ResourceManager.GetString("IssuesMatchBase_IssueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Request.
        /// </summary>
        public static string IssuesMatchBase_PullRequestLabel {
            get {
                return ResourceManager.GetString("IssuesMatchBase_PullRequestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find issues in the milestone.
        /// </summary>
        public static string MilestoneMatch_SearchHint {
            get {
                return ResourceManager.GetString("MilestoneMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone.
        /// </summary>
        public static string MilestonesMatch_Label {
            get {
                return ResourceManager.GetString("MilestonesMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find milestones.
        /// </summary>
        public static string MilestonesMatch_SearchHint {
            get {
                return ResourceManager.GetString("MilestonesMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Repository.
        /// </summary>
        public static string NewMatch_ImportRepository {
            get {
                return ResourceManager.GetString("NewMatch_ImportRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Codespace.
        /// </summary>
        public static string NewMatch_NewCodespace {
            get {
                return ResourceManager.GetString("NewMatch_NewCodespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Gist.
        /// </summary>
        public static string NewMatch_NewGist {
            get {
                return ResourceManager.GetString("NewMatch_NewGist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Issue.
        /// </summary>
        public static string NewMatch_NewIssue {
            get {
                return ResourceManager.GetString("NewMatch_NewIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Organization.
        /// </summary>
        public static string NewMatch_NewOrganization {
            get {
                return ResourceManager.GetString("NewMatch_NewOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Pull Request.
        /// </summary>
        public static string NewMatch_NewPullRequest {
            get {
                return ResourceManager.GetString("NewMatch_NewPullRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Repository.
        /// </summary>
        public static string NewMatch_NewRepository {
            get {
                return ResourceManager.GetString("NewMatch_NewRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub New.
        /// </summary>
        public static string NewsMatch_Label {
            get {
                return ResourceManager.GetString("NewsMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find item to create.
        /// </summary>
        public static string NewsMatch_SearchHint {
            get {
                return ResourceManager.GetString("NewsMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find issues and pull requests in the project.
        /// </summary>
        public static string ProjectMatch_SearchHint {
            get {
                return ResourceManager.GetString("ProjectMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Project.
        /// </summary>
        public static string ProjectsMatch_Label {
            get {
                return ResourceManager.GetString("ProjectsMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find projects.
        /// </summary>
        public static string ProjectsMatch_SearchHint {
            get {
                return ResourceManager.GetString("ProjectsMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find pull requests.
        /// </summary>
        public static string PullRequestsMatch_SearchHint {
            get {
                return ResourceManager.GetString("PullRequestsMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Repository.
        /// </summary>
        public static string RepositoriesMatch_Label {
            get {
                return ResourceManager.GetString("RepositoriesMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My GitHub Repository.
        /// </summary>
        public static string RepositoriesMatch_MyLabel {
            get {
                return ResourceManager.GetString("RepositoriesMatch_MyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find repositories.
        /// </summary>
        public static string RepositoriesMatch_SearchHint {
            get {
                return ResourceManager.GetString("RepositoriesMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find issues.
        /// </summary>
        public static string RepositoryMatch_SearchHint {
            get {
                return ResourceManager.GetString("RepositoryMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find repositories.
        /// </summary>
        public static string UserMatch_SearchHint {
            get {
                return ResourceManager.GetString("UserMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub User.
        /// </summary>
        public static string UsersMatch_Label {
            get {
                return ResourceManager.GetString("UsersMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find users.
        /// </summary>
        public static string UsersMatch_SearchHint {
            get {
                return ResourceManager.GetString("UsersMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Run.
        /// </summary>
        public static string WorkflowRunsMatch_Label {
            get {
                return ResourceManager.GetString("WorkflowRunsMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find workflow runs.
        /// </summary>
        public static string WorkflowRunsMatch_SearchHint {
            get {
                return ResourceManager.GetString("WorkflowRunsMatch_SearchHint", resourceCulture);
            }
        }
    }
}
