//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tql.Plugins.GitHub {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tql.Plugins.GitHub.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Button_Update {
            get {
                return ResourceManager.GetString("Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string ConfigurationControl_Connections {
            get {
                return ResourceManager.GetString("ConfigurationControl_Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string ConfigurationControl_General {
            get {
                return ResourceManager.GetString("ConfigurationControl_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ConfigurationControl_Name {
            get {
                return ResourceManager.GetString("ConfigurationControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string ConfigurationControl_NameLabel {
            get {
                return ResourceManager.GetString("ConfigurationControl_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate with GitHub.
        /// </summary>
        public static string DeviceCodeWindow_AuthenticationWithGitHub {
            get {
                return ResourceManager.GetString("DeviceCodeWindow_AuthenticationWithGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the button below to go to the GitHub website and enter the user code shown below:.
        /// </summary>
        public static string DeviceCodeWindow_HelpText {
            get {
                return ResourceManager.GetString("DeviceCodeWindow_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Device Activation page.
        /// </summary>
        public static string DeviceCodeWindow_OpenDeviceActivationPage {
            get {
                return ResourceManager.GetString("DeviceCodeWindow_OpenDeviceActivationPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Authentication.
        /// </summary>
        public static string DeviceCodeWindow_Title {
            get {
                return ResourceManager.GetString("DeviceCodeWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Gist.
        /// </summary>
        public static string GistsMatch_Label {
            get {
                return ResourceManager.GetString("GistsMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My GitHub Gist.
        /// </summary>
        public static string GistsMatch_MyLabel {
            get {
                return ResourceManager.GetString("GistsMatch_MyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find gists.
        /// </summary>
        public static string GistsMatch_SearchHint {
            get {
                return ResourceManager.GetString("GistsMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub - {0}.
        /// </summary>
        public static string GitHubApi_ResourceName {
            get {
                return ResourceManager.GetString("GitHubApi_ResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to {0}. Click here to reconnect..
        /// </summary>
        public static string GitHubApi_UnableToConnect {
            get {
                return ResourceManager.GetString("GitHubApi_UnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string GitHubPlugin_Title {
            get {
                return ResourceManager.GetString("GitHubPlugin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find issues.
        /// </summary>
        public static string IssuesMatch_SearchHint {
            get {
                return ResourceManager.GetString("IssuesMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Issue.
        /// </summary>
        public static string IssuesMatchBase_IssueLabel {
            get {
                return ResourceManager.GetString("IssuesMatchBase_IssueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My GitHub Issue.
        /// </summary>
        public static string IssuesMatchBase_MyIssueLabel {
            get {
                return ResourceManager.GetString("IssuesMatchBase_MyIssueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My GitHub Pull Request.
        /// </summary>
        public static string IssuesMatchBase_MyPullRequestLabel {
            get {
                return ResourceManager.GetString("IssuesMatchBase_MyPullRequestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Pull Request.
        /// </summary>
        public static string IssuesMatchBase_PullRequestLabel {
            get {
                return ResourceManager.GetString("IssuesMatchBase_PullRequestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find item to create.
        /// </summary>
        public static string NewsMatch_SearchHint {
            get {
                return ResourceManager.GetString("NewsMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find pull requests.
        /// </summary>
        public static string PullRequestsMatch_SearchHint {
            get {
                return ResourceManager.GetString("PullRequestsMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Repository.
        /// </summary>
        public static string RepositoriesMatch_Label {
            get {
                return ResourceManager.GetString("RepositoriesMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My GitHub Repository.
        /// </summary>
        public static string RepositoriesMatch_MyLabel {
            get {
                return ResourceManager.GetString("RepositoriesMatch_MyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find repositories.
        /// </summary>
        public static string RepositoriesMatch_SearchHint {
            get {
                return ResourceManager.GetString("RepositoriesMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find issues.
        /// </summary>
        public static string RepositoryMatch_SearchHint {
            get {
                return ResourceManager.GetString("RepositoryMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find repositories.
        /// </summary>
        public static string UserMatch_SearchHint {
            get {
                return ResourceManager.GetString("UserMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub User.
        /// </summary>
        public static string UsersMatch_Label {
            get {
                return ResourceManager.GetString("UsersMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find users.
        /// </summary>
        public static string UsersMatch_SearchHint {
            get {
                return ResourceManager.GetString("UsersMatch_SearchHint", resourceCulture);
            }
        }
    }
}
