source "https://rubygems.org"

gem "jekyll", "4.3.2"
gem "just-the-docs", "0.4.0.rc1"

gem "webrick", "1.8.1"  # required for ruby 3.0+
gem "wdm", "0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
