name: Update GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: windows-2022

    steps:
      - name: Authenticate GitHub package source
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/TQLApp/index.json"

      - uses: actions/checkout@v4

      - name: Get Last Build Version
        id: get-build-version
        shell: pwsh
        run: ./Build/GetBuildVersion.ps1

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-v2-${{ hashFiles('**/packages.lock.json') }}

      - name: Restore Solution
        run: msbuild -nodeReuse:false -maxCpuCount -target:Restore -property:Configuration="Release" -property:Version="${{ steps.get-build-version.outputs.build-version }}" Tql.sln

      - name: Build Solution
        run: msbuild -nodeReuse:false -maxCpuCount -target:Build -property:Configuration="Release" -property:Version="${{ steps.get-build-version.outputs.build-version }}" Tql.sln

      - name: Install DocFX
        run: dotnet tool update -g docfx

      - name: Run DocFX
        run: docfx Documentation/docfx.json

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload DocFX Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "Documentation/_site"

  deploy-pages:
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    name: Deploy pages

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
