name: PR build

on: pull_request

jobs:
  pr-build:
    name: PR build
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet 8.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-v2-${{ hashFiles('**/packages.lock.json') }}

      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Validate prettier
        run: ./runprettier.bat

      - name: Check for changes by prettier
        shell: pwsh
        run: ./scripts/Uncommitted-changes.ps1 -Tool runprettier.bat

      - name: Run CSharpier
        run: dotnet csharpier .

      - name: Check for changes by CSharpier
        shell: pwsh
        run: ./scripts/Uncommitted-changes.ps1 -Tool "dotnet csharpier ."

      - name: Restore Solution
        run: dotnet restore -warnaserror

      - name: Embedding secrets
        shell: pwsh
        run: ./scripts/Write-Secrets.ps1
        env:
          GOOGLE_DRIVE_API_SECRET: ${{ secrets.GOOGLE_DRIVE_API_SECRET }}

      - name: Build Solution
        run: dotnet build -c Release -warnaserror

      - name: Check localization status
        shell: pwsh
        run: .\src\Tql.Localization\bin\Release\net8.0-windows\Tql.Localization.exe --export --filename Strings.xlsx --locale nl --pipeline

      - name: Preprocess DocFX Markdown Files
        shell: pwsh
        run: ./scripts/Preprocess-Markdown.ps1

      - name: Run DocFX
        run: dotnet docfx docs/docfx.json --warningsAsErrors true
