name: PR build

on: pull_request

jobs:
  pr-build:
    name: PR build
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet 8.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-v2-${{ hashFiles('**/packages.lock.json') }}

      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Validate prettier
        run: ./runprettier.bat

      - name: Check for changes by prettier
        shell: pwsh
        run: ./Build/Uncommitted-changes.ps1 -tool runprettier.bat
        continue-on-error: true

      - name: Run CSharpier
        run: dotnet csharpier .

      - name: Check for changes by CSharpier
        shell: pwsh
        run: ./Build/Uncommitted-changes.ps1 -tool "dotnet csharpier ."
        continue-on-error: true

      - name: Restore Solution
        run: dotnet restore -warnaserror

      - name: Build Solution
        run: dotnet build -c Release -warnaserror

      - name: Check localization status
        shell: pwsh
        run: .\Tql.Localization\bin\Release\net8.0-windows\Tql.Localization.exe --export --filename Strings.xlsx --locale nl --pipeline
        continue-on-error: true

      - name: Preprocess DocFX Markdown Files
        shell: pwsh
        run: ./Build/Preprocess-Markdown.ps1

      - name: Run DocFX
        run: dotnet docfx Documentation/docfx.json

      - name: Check for errors
        if: ${{ failure() }}
        run: exit 1
