name: PR build

on: pull_request

jobs:
  pr-build:
    name: PR build
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-v2-${{ hashFiles('**/packages.lock.json') }}

      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Validate prettier
        run: ./runprettier.bat

      - name: Check for changes by prettier
        shell: pwsh
        run: ./Build/Uncommitted-changes.ps1 -tool runprettier.bat

      - name: Run CSharpier
        run: dotnet csharpier .

      - name: Check for changes by CSharpier
        shell: pwsh
        run: ./Build/Uncommitted-changes.ps1 -tool "dotnet csharpier ."

      - name: Restore Solution
        run: msbuild -nodeReuse:false -maxCpuCount -target:Restore -property:Configuration="Release" -warnaserror Tql.sln

      - name: Build Solution
        run: msbuild -nodeReuse:false -maxCpuCount -target:Build -property:Configuration="Release" -warnaserror Tql.sln

      - name: Preprocess DocFX Markdown Files
        shell: pwsh
        run: ./Build/Preprocess-Markdown.ps1

      - name: Run DocFX
        run: docfx Documentation/docfx.json
