name: PR build

on: pull_request

jobs:
  pr-build:
    name: PR build
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet 8.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Validate prettier
        run: ./runprettier.bat

      - name: Check for changes by prettier
        shell: pwsh
        run: ./Build/Uncommitted-changes.ps1 -tool runprettier.bat

      - name: Install CSharpier
        run: dotnet tool restore

      - name: Run CSharpier
        run: dotnet csharpier .

      - name: Check for changes by CSharpier
        shell: pwsh
        run: ./Build/Uncommitted-changes.ps1 -tool "dotnet csharpier ."

      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-v2-${{ hashFiles('**/packages.lock.json') }}

      - name: Restore Solution
        run: dotnet restore -c Release

      - name: Build Solution
        run: dotnet build -c Release

      - name: Install DocFX
        run: dotnet tool update -g docfx

      - name: Preprocess DocFX Markdown Files
        shell: pwsh
        run: ./Build/Preprocess-Markdown.ps1

      - name: Run DocFX
        run: docfx Documentation/docfx.json
