//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tql.Plugins.AzureDevOps {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tql.Plugins.AzureDevOps.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure DevOps - {0}.
        /// </summary>
        public static string AzureDevOpsApi_ResourceName {
            get {
                return ResourceManager.GetString("AzureDevOpsApi_ResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to {0}. Click here to open the {1} settings screen and validate your credentials..
        /// </summary>
        public static string AzureDevOpsApi_UnableToConnect {
            get {
                return ResourceManager.GetString("AzureDevOpsApi_UnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure DevOps - {0}.
        /// </summary>
        public static string AzureDevOpsPeopleDirectory_Name {
            get {
                return ResourceManager.GetString("AzureDevOpsPeopleDirectory_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure DevOps.
        /// </summary>
        public static string AzureDevOpsPlugin_Title {
            get {
                return ResourceManager.GetString("AzureDevOpsPlugin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Backlog.
        /// </summary>
        public static string BacklogMatch_Label {
            get {
                return ResourceManager.GetString("BacklogMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find work items.
        /// </summary>
        public static string BacklogMatch_SearchHint {
            get {
                return ResourceManager.GetString("BacklogMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure DevOps Backlog.
        /// </summary>
        public static string BacklogsMatch_Label {
            get {
                return ResourceManager.GetString("BacklogsMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find backlogs.
        /// </summary>
        public static string BacklogsMatch_SearchHint {
            get {
                return ResourceManager.GetString("BacklogsMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Board.
        /// </summary>
        public static string BoardMatch_Label {
            get {
                return ResourceManager.GetString("BoardMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find work items.
        /// </summary>
        public static string BoardMatch_SearchHint {
            get {
                return ResourceManager.GetString("BoardMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure DevOps Board.
        /// </summary>
        public static string BoardsMatch_Label {
            get {
                return ResourceManager.GetString("BoardsMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find boards.
        /// </summary>
        public static string BoardsMatch_SearchHint {
            get {
                return ResourceManager.GetString("BoardsMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Button_Documentation {
            get {
                return ResourceManager.GetString("Button_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string ConfigurationControl_Connections {
            get {
                return ResourceManager.GetString("ConfigurationControl_Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string ConfigurationControl_General {
            get {
                return ResourceManager.GetString("ConfigurationControl_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ConfigurationControl_Name {
            get {
                return ResourceManager.GetString("ConfigurationControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string ConfigurationControl_URL {
            get {
                return ResourceManager.GetString("ConfigurationControl_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string ConnectionEditWindow_NameLabel {
            get {
                return ResourceManager.GetString("ConnectionEditWindow_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create a PAT token in the Azure DevOps website. You can find more information on the documentation page. Use the Documentation link above to open the documentation page..
        /// </summary>
        public static string ConnectionEditWindow_PATTokenHelpText {
            get {
                return ResourceManager.GetString("ConnectionEditWindow_PATTokenHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAT token:.
        /// </summary>
        public static string ConnectionEditWindow_PATTokenLabel {
            get {
                return ResourceManager.GetString("ConnectionEditWindow_PATTokenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Connection.
        /// </summary>
        public static string ConnectionEditWindow_Title {
            get {
                return ResourceManager.GetString("ConnectionEditWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This URL is the URL to your Azure DevOps environment. It should similar to https://dev.azure.com/yourcompany..
        /// </summary>
        public static string ConnectionEditWindow_URLHelpText {
            get {
                return ResourceManager.GetString("ConnectionEditWindow_URLHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL:.
        /// </summary>
        public static string ConnectionEditWindow_URLLabel {
            get {
                return ResourceManager.GetString("ConnectionEditWindow_URLLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Dashboard.
        /// </summary>
        public static string DashboardMatch_Label {
            get {
                return ResourceManager.GetString("DashboardMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure DevOps Dashboard.
        /// </summary>
        public static string DashboardsMatch_Label {
            get {
                return ResourceManager.GetString("DashboardsMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find dashboards.
        /// </summary>
        public static string DashboardsMatch_SearchHint {
            get {
                return ResourceManager.GetString("DashboardsMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {0}.
        /// </summary>
        public static string NewMatch_NewIssueType {
            get {
                return ResourceManager.GetString("NewMatch_NewIssueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Query.
        /// </summary>
        public static string NewMatch_NewQuery {
            get {
                return ResourceManager.GetString("NewMatch_NewQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure DevOps New.
        /// </summary>
        public static string NewsMatch_Label {
            get {
                return ResourceManager.GetString("NewsMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find item to create.
        /// </summary>
        public static string NewsMatch_SearchHint {
            get {
                return ResourceManager.GetString("NewsMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure DevOps Pipeline.
        /// </summary>
        public static string PipelinesMatch_Label {
            get {
                return ResourceManager.GetString("PipelinesMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find pipelines.
        /// </summary>
        public static string PipelinesMatch_SearchHint {
            get {
                return ResourceManager.GetString("PipelinesMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure DevOps Query.
        /// </summary>
        public static string QueriesMatch_Label {
            get {
                return ResourceManager.GetString("QueriesMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find queries.
        /// </summary>
        public static string QueriesMatch_SearchHint {
            get {
                return ResourceManager.GetString("QueriesMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find work items.
        /// </summary>
        public static string QueryMatch_SearchHint {
            get {
                return ResourceManager.GetString("QueryMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure DevOps Repository.
        /// </summary>
        public static string RepositoriesMatch_Label {
            get {
                return ResourceManager.GetString("RepositoriesMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find repositories.
        /// </summary>
        public static string RepositoriesMatch_SearchHint {
            get {
                return ResourceManager.GetString("RepositoriesMatch_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find files.
        /// </summary>
        public static string RepositoryMatch_FindFiles {
            get {
                return ResourceManager.GetString("RepositoryMatch_FindFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure DevOps Work Item.
        /// </summary>
        public static string WorkItemsMatch_Label {
            get {
                return ResourceManager.GetString("WorkItemsMatch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find work items.
        /// </summary>
        public static string WorkItemsMatch_SearchHint {
            get {
                return ResourceManager.GetString("WorkItemsMatch_SearchHint", resourceCulture);
            }
        }
    }
}
